db_client = "mongodb://localhost:27017"
bse_equities_reference = r""
database_name = "AlgoTradingSource"
collection_name = "StockPricesData"
timeseries_collection = "StockPriceDataTimeSeries"
past24month_collection = "LastOneYearStockData"
